name: CI with GTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive
    - name: configure
      run: cmake -S . -B build/
    - name: make
      run: make
    - name: ctest
      run: env --chdir cmake-build-debug ctest
