name: Unit tests

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install gcc g++
      shell: bash
      run: |
        sudo apt install -y gcc g++
    - name: configure
      run: cmake -S . -B build/ -DLIBAVIF_CONTAINER_BUILD_TESTS=ON
    - name: make
      run: env --chdir build make
    - name: ctest
      run: env --chdir build ctest
