name: Unit tests

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install gcc-8 g++-8
      shell: bash
      run: |
        sudo apt install -y gcc-8 g++-8
    - name: configure
      run: CXX=g++-8 CC=gcc-8 cmake -S . -B build/ -DLIBAVIF_CONTAINER_BUILD_TESTS=ON
    - name: make
      run: env --chdir build make
    - name: ctest
      run: env --chdir build ctest
